In [100]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
customers = pd.read_csv('data_like/customer_train.csv')
hack = pd.read_excel('data_like/Hack_desc.xlsx')
stories = pd.read_csv('data_like/stories_description.csv')
reaction = pd.read_csv('data_like/stories_reaction_train.csv')
transactions = pd.read_csv('data_like/transactions.csv')

In [140]:
transactions

customer_id  transaction_month  transaction_day  transaction_amt  \
0             855115                  7                3             1500   
1             997036                  6                6                0   
2             398237                  5               24             2500   
3             997036                  6                2                0   
4             291636                  7               25                0   
5             844503                  5               24             3500   
6             844503                  6               22             3500   
7             862192                  7               14                0   
8             862192                  5               26                0   
9             862192                  7               11                0   
10            862192                  7               23                0   
11            564201                  7                5                0   
12            564201                  7                3                0   
13            661331                  6                6                0   
14            408749                  6               12             1500   
15            564201                  7               24                0   
16            862192                  7                9                0   
17            177124                  5               31             6500   
18            862192                  7               18                0   
19            177826                  7                1             1500   
20            895631                  5               28             1000   
21            194526                  6                9                0   
22            194526                  7                9                0   
23            479673                  7               24                0   
24            479673                  7               24                0   
25            375979                  6               10             5000   
26            296423                  6               23             4000   
27            862312                  6               24                0   
28             36823                  7               22                0   
29             36823                  6               10                0   
...              ...                ...              ...              ...   
3951085       901050                  7                3                0   
3951086       901050                  6               27                0   
3951087       901050                  5               24                0   
3951088       901050                  6                6                0   
3951089       901050                  7                4                0   
3951090       901050                  6                4                0   
3951091       901050                  6                4                0   
3951092       901050                  7                4                0   
3951093        24846                  6               21              500   
3951094       819012                  6                7              500   
3951095       257682                  6               10             4000   
3951096       783482                  6               22             1500   
3951097       289468                  7               23                0   
3951098       289468                  6                2                0   
3951099       603825                  6                4                0   
3951100       246968                  6               22             6000   
3951101       303082                  7                2             1000   
3951102       561987                  7                8                0   
3951103       561987                  7                1                0   
3951104       561987                  7                8                0   
39511

In [9]:
customers.head()

customer_id product_0 product_1 product_2 product_3 product_4 product_5  \
0       894436       NaN       NaN       NaN       NaN       NaN       UTL   
1       524526       NaN       UTL       NaN       NaN       NaN       UTL   
2       498134       NaN       UTL       NaN       NaN       NaN       NaN   
3       278941       NaN       NaN       UTL       CLS       NaN       UTL   
4       877312       NaN       UTL       NaN       NaN       NaN       NaN   

  product_6 gender_cd   age marital_status_cd  children_cnt  \
0       NaN         M  30.0               MAR           0.0   
1       NaN         F  20.0               UNM           0.0   
2       NaN         F  25.0               UNM           0.0   
3       UTL         M  25.0               NaN           NaN   
4       NaN         F  40.0               MAR           0.0   

    first_session_dttm  job_position_cd  \
0  2018-03-20 09:10:16                1   
1  2017-03-29 20:38:45               16   
2  2018-03-12 11:25:06               22   
3  2016-02-21 18:47:51               16   
4  2018-03-07 11:17:02               22   

                                  job_title  
0  Неруководящий сотрудник - обсл. Персонал  
1                                       NaN  
2                                       NaN  
3      Неруководящий сотрудник - специалист  
4                                       NaN

In [23]:
hack.values

array([['customer_id', 'Идентификатор клиента'],
       ['product_X',
        'Статус продукта. OPN - открыт, но не утилизирован. UTL - утилизирован. CLS - закрыт'],
       ['gender_cd', 'Пол. M - мужской. F - женский'],
       ['age', 'Возраст в годах'],
       ['marital_status_cd', 'Семейный статус. См. словарь соответствия'],
       ['children_cnt', 'Количество детей в штуках'],
       ['first_session_dttm',
        'Дата и время первой сессии в приложении или личном кабинете на сайте'],
       ['job_position_cd',
        'Категория занимаемой должности. См. словарь соответствия'],
       ['job_title', 'Занимаемая должность'],
       [nan, nan],
       ['transactions', nan],
       ['customer_id', 'Идентификатор клиента'],
       ['transaction_month', 'Месяц транзакции'],
       ['transaction_day', 'День транзакции'],
       ['transaction_amt', 'Сумма транзакции в рублях'],
       ['merchant_id',
        'Идентификатор магазина, в котором была совершена транзакция'],
       ['mercha

In [12]:
reaction.head()

customer_id  story_id           event_dttm event
0           15       138  2018-07-24 15:33:22  view
1           15       202  2018-06-04 08:08:08  skip
2           15       222  2018-06-17 13:44:45  skip
3           15       379  2018-05-23 05:41:43  skip
4           15       544  2018-07-25 02:16:29  view

In [13]:
transactions.head()

customer_id  transaction_month  transaction_day  transaction_amt  \
0       855115                  7                3             1500   
1       997036                  6                6                0   
2       398237                  5               24             2500   
3       997036                  6                2                0   
4       291636                  7               25                0   

   merchant_id  merchant_mcc  
0      4554547          5411  
1      1657528          5411  
2     26375569          5813  
3     16304402          5411  
4      1259505          5411

In [14]:
stories.head()

story_id                                         story_json
0       127  {"guid":"770a5bae-0e3f-4a6b-b924-bd87bd51a038"...
1       254  {"guid":"64f4c9ef-647b-4e04-b4d4-02297e939388"...
2       865  {"guid":"3482206b-d223-4aec-92ba-0150055cd68a"...
3      1491  {"guid":"5f4a9215-01de-4777-b70f-a18899db8f1c"...
4       598  {"guid":"ed8754bd-67be-4fa1-9289-5508d96f1fa4"...

In [19]:
stories.values[1]

array([254,
       '{"guid":"64f4c9ef-647b-4e04-b4d4-02297e939388","type":"root","description":"https://wiki.tcsbank.ru/pages/viewpage.action?pageId=276651383","properties":{"name":"Пополнить «Стрелку»","background":{"gradient":{"colors":[],"direction":"vertical"},"blur":false},"icon_url":"https://static2.tinkoff.ru/portfolio/stories/icons/strelka_icon_18-07_zahod.png","icon_background":{"gradient":{"colors":[{"hex":"#b8a1e0","alpha":1},{"hex":"#00bee0","alpha":1}],"direction":"vertical"},"blur":false},"hide_page_status":false},"content":[{"guid":"dad1c413-2f10-438d-82b4-7a02d22b93ed","type":"story-page","properties":{"topMask":false,"bottomMask":false,"flip_interval":10,"background":{"gradient":{"colors":[{"hex":"#b8a1e0","alpha":1},{"hex":"#00bee0","alpha":1}],"direction":"diagonal"},"blur":false},"hidden":"false","disable_tap_zones":false,"log_view":false},"content":[{"guid":"4f83ea53-33f7-4654-8b77-7971f3438be2","type":"layout-linear","properties":{"orientation":"vertical","topMask

In [38]:
reaction['event'].unique()

array(['view', 'skip', 'like', 'dislike'], dtype=object)

In [33]:
customers[['product_{}'.format(i) for i in range(6)]].describe()

product_0 product_1 product_2 product_3 product_4 product_5
count       1599     23725      4391      6813      2182     33426
unique         2         3         3         2         3         3
top          UTL       UTL       UTL       UTL       UTL       UTL
freq        1582     20412      1895      3725      1384     32078

In [36]:
customers['product_0'].unique()

array([nan, 'UTL', 'CLS'], dtype=object)

In [46]:
reaction.groupby('event').count()['customer_id']/reaction.shape[0]

event
dislike    0.013896
like       0.119810
skip       0.354159
view       0.512135
Name: customer_id, dtype: float64

In [67]:
reaction['event_dttm'] = pd.to_datetime(reaction['event_dttm'])
reaction.set_index('event_dttm', inplace=True)

In [92]:
reaction['Morning'] = (reaction.index.hour<12).astype('int')
reaction['Evening'] = (reaction.index.hour>18).astype('int')
reaction['Midday'] = np.all([reaction.index.hour<=18, reaction.index.hour>=12], axis=0).astype('int')

In [91]:
np.all([reaction.index.hour<=18, reaction.index.hour>=12], axis=0).astype('int')

array([1, 0, 1, ..., 0, 0, 0])

In [84]:
reaction.index.hour<=6

array([False, False, False, ...,  True, False,  True])

In [85]:
reaction.index.hour>=12

array([ True, False,  True, ..., False,  True, False])

In [88]:
reaction.index.hour

Int64Index([15,  8, 13,  5,  2,  1, 15,  5,  8,  9,
            ...
             8, 10, 19,  6, 19,  6, 19,  6, 19,  6],
           dtype='int64', name='event_dttm', length=473141)

In [95]:
reaction[reaction['Evening'] == 1].groupby('event').count()['customer_id']/reaction['Evening'].sum()

event
dislike    0.013806
like       0.121553
skip       0.334123
view       0.530518
Name: customer_id, dtype: float64

In [96]:
reaction[reaction['Morning'] == 1].groupby('event').count()['customer_id']/reaction['Morning'].sum()

event
dislike    0.013787
like       0.121159
skip       0.353936
view       0.511117
Name: customer_id, dtype: float64

In [97]:
reaction['Morning'].sum()

291352

In [98]:
reaction['Midday'].sum()

154772

In [99]:
reaction[reaction['Midday'] == 1].groupby('event').count()['customer_id']/reaction['Midday'].sum()

event
dislike    0.014118
like       0.116966
skip       0.358075
view       0.510842
Name: customer_id, dtype: float64

In [138]:
loyal = reaction.groupby('customer_id').count()[(reaction.groupby('customer_id').count()['story_id'] > 100)].index
customers[customers['customer_id'].apply(lambda x: x in loyal)]

customer_id product_0 product_1 product_2 product_3 product_4  \
187         335762       NaN       NaN       NaN       NaN       NaN   
201         575563       NaN       NaN       UTL       NaN       NaN   
299         471549       NaN       NaN       UTL       NaN       NaN   
395         703390       NaN       UTL       NaN       NaN       NaN   
434         508636       NaN       NaN       OPN       NaN       NaN   
684         341384       NaN       NaN       NaN       NaN       NaN   
850         201384       NaN       NaN       NaN       NaN       NaN   
854         168303       NaN       NaN       NaN       NaN       NaN   
1038        662972       NaN       UTL       NaN       UTL       NaN   
1208        218142       NaN       UTL       UTL       NaN       NaN   
1372        185715       NaN       NaN       NaN       CLS       NaN   
1397        809054       NaN       UTL       NaN       NaN       NaN   
1410        227218       NaN       NaN       NaN       CLS       NaN   
1454        369530       NaN       NaN       CLS       CLS       NaN   
1478        465339       NaN       NaN       NaN       NaN       NaN   
1507        146597       NaN       NaN       NaN       CLS       NaN   
1513        618745       NaN       NaN       NaN       NaN       NaN   
1585        917520       NaN       CLS       UTL       NaN       NaN   
1590        332300       NaN       NaN       NaN       UTL       NaN   
1655        718950       NaN       NaN       NaN       CLS       NaN   
1676         95578       NaN       NaN       UTL       NaN       NaN   
1742        597097       NaN       UTL       NaN       NaN       NaN   
1883        623355       NaN       UTL       NaN       NaN       NaN   
1920        661419       NaN       NaN       NaN       NaN       NaN   
1944        714602       NaN       NaN       NaN       NaN       NaN   
1973        387994       NaN       NaN       NaN       UTL       NaN   
2078        268960       NaN       UTL       NaN       NaN       NaN   
2154        397532       UTL       NaN       NaN       NaN       NaN   
2174        673801       NaN       NaN       NaN       CLS       NaN   
2272        192859       NaN       UTL       NaN       UTL       NaN   
...            ...       ...       ...       ...       ...       ...   
48158       293779       NaN       NaN       NaN       NaN       CLS   
48178       280534       NaN       UTL       NaN       CLS       NaN   
48260       742954       NaN       NaN       NaN       NaN       NaN   
48324       478369       NaN       NaN       UTL       NaN       NaN   
48346       644377       NaN       NaN       NaN       NaN       NaN   
48360        86179       NaN       NaN       NaN       NaN       NaN   
48362       410629       NaN       NaN       NaN       NaN       NaN   
48369       622372       NaN       UTL       NaN       NaN       NaN   
48384       499959       NaN       NaN       CLS       UTL       NaN   
48403       956069       NaN       NaN       NaN       NaN       NaN   
48415       789704       NaN       NaN       NaN       NaN       NaN   
48489       104248       NaN       UTL       UTL       NaN       NaN   
48491       953319       NaN       NaN       NaN       NaN       NaN   
48531       597700       NaN       NaN       CLS       NaN       NaN   
48691       297343       NaN       UTL       CLS       NaN       UTL   
48865       475522       NaN       NaN       UTL       NaN       NaN   
48902       404594       NaN       NaN       UTL       NaN       NaN   
49068       169371       NaN       NaN       NaN       UTL       NaN   
49085       316837       NaN       NaN       NaN       NaN       NaN   
49146       221936       NaN       UTL       NaN       NaN       NaN   
49299       385659       UTL       UTL       UTL       CLS       NaN   
49356       111287       NaN       CLS       NaN       CLS       NaN   
49402       468526       NaN       NaN       UTL       CLS       NaN   
49540       778689       NaN       NaN       Na

In [139]:
unloyal = reaction.groupby('customer_id').count()[(reaction.groupby('customer_id').count()['story_id'] < 5)].index
customers[customers['customer_id'].apply(lambda x: x in unloyal)]

customer_id product_0 product_1 product_2 product_3 product_4  \
4           877312       NaN       UTL       NaN       NaN       NaN   
5           821806       NaN       NaN       NaN       UTL       NaN   
6           782728       NaN       UTL       NaN       NaN       NaN   
7           540071       NaN       NaN       NaN       NaN       NaN   
13          307008       NaN       CLS       UTL       NaN       NaN   
21          143055       NaN       UTL       NaN       NaN       NaN   
24          195762       NaN       CLS       NaN       NaN       NaN   
26          761975       NaN       UTL       NaN       NaN       NaN   
33          303498       NaN       UTL       NaN       NaN       NaN   
36          341657       NaN       NaN       NaN       UTL       NaN   
43          122515       NaN       NaN       NaN       NaN       NaN   
44          167588       NaN       NaN       NaN       NaN       NaN   
49           99627       NaN       NaN       NaN       NaN       NaN   
50           63986       NaN       NaN       NaN       NaN       NaN   
51          837267       NaN       UTL       NaN       NaN       NaN   
53          651142       NaN       NaN       NaN       NaN       NaN   
55          899183       NaN       UTL       NaN       NaN       NaN   
60          526279       UTL       UTL       NaN       NaN       NaN   
62          757900       NaN       CLS       NaN       NaN       NaN   
64           15142       NaN       CLS       NaN       CLS       NaN   
70            6104       NaN       CLS       NaN       NaN       NaN   
73          955325       NaN       NaN       NaN       NaN       NaN   
77          231802       NaN       UTL       NaN       NaN       NaN   
80          947839       NaN       NaN       NaN       NaN       NaN   
81          696013       NaN       NaN       NaN       NaN       NaN   
85          173789       NaN       NaN       NaN       CLS       NaN   
86           23678       NaN       CLS       NaN       NaN       NaN   
87          859062       NaN       NaN       NaN       UTL       NaN   
90          519337       NaN       UTL       NaN       NaN       NaN   
91          866732       NaN       UTL       NaN       NaN       NaN   
...            ...       ...       ...       ...       ...       ...   
49928       802622       NaN       UTL       NaN       NaN       NaN   
49930       680531       NaN       UTL       NaN       NaN       NaN   
49931       711728       NaN       UTL       NaN       NaN       NaN   
49933       544173       NaN       NaN       NaN       NaN       NaN   
49938       307687       NaN       NaN       NaN       UTL       NaN   
49940       425909       NaN       NaN       NaN       NaN       NaN   
49947       726583       NaN       NaN       CLS       UTL       NaN   
49952       678509       NaN       NaN       NaN       NaN       NaN   
49953       176006       NaN       NaN       NaN       NaN       NaN   
49954        65704       NaN       OPN       NaN       NaN       NaN   
49955       356728       NaN       UTL       NaN       NaN       NaN   
49958       697827       NaN       NaN       NaN       CLS       NaN   
49961       729128       UTL       UTL       NaN       NaN       NaN   
49962       188975       NaN       NaN       NaN       CLS       NaN   
49964       890431       NaN       UTL       NaN       NaN       NaN   
49965       673818       NaN       UTL       UTL       UTL       NaN   
49969       677177       NaN       UTL       NaN       NaN       NaN   
49970       456376       NaN       NaN       NaN       NaN       NaN   
49971       683014       NaN       NaN       NaN       NaN       NaN   
49972       480933       NaN       UTL       NaN       NaN       NaN   
49973        41434       NaN       UTL       NaN       NaN       NaN   
49977       956410       NaN       NaN       NaN       NaN       NaN   
49981       621810       NaN       NaN       NaN       NaN       NaN   
49982       381440       UTL       NaN       Na